<?php

/**
 * This is the model base class for the table "room".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Room".
 *
 * Columns in table "room" available as properties of the model,
 * followed by relations of table "room" available as properties of the model.
 *
 * @property integer $room_id
 * @property string $room_name
 *
 * @property ExitAppointment[] $exitAppointments
 */
abstract class BaseRoom extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'room';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Room|Rooms', $n);
	}

	public static function representingColumn() {
		return 'room_name';
	}

	public function rules() {
		return array(
			array('room_name', 'required'),
			array('room_name', 'length', 'max'=>45),
			array('room_id, room_name', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'exitAppointments' => array(self::HAS_MANY, 'ExitAppointment', 'appointment_room_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'room_id' => Yii::t('app', 'Room'),
			'room_name' => Yii::t('app', 'Room Name'),
			'exitAppointments' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('room_id', $this->room_id);
		$criteria->compare('room_name', $this->room_name, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}